pdf:
	pandoc \
          --pdf-engine xelatex \
	  --variable mainfont="DejaVu Sans" \
	  --variable sansfont="DejaVu Sans" \
          -V geometry:"top=3cm, bottom=3cm, left=3.2cm, right=3.2cm" \
	  -V fontsize=11pt \
          -V papersize:a4 \
	  -o Kurzreferenz_git.pdf \
	  Kurzreferenz_git.md

	pandoc \
          --pdf-engine xelatex \
	  --variable mainfont="DejaVu Sans" \
	  --variable sansfont="DejaVu Sans" \
          -V geometry:"top=3cm, bottom=3cm, left=3.2cm, right=3.2cm" \
	  -V fontsize=11pt \
          -V papersize:a4 \
	  -o shortreference_python.pdf \
	  shortreference_python.md

	pandoc \
          --pdf-engine xelatex \
	  --variable mainfont="DejaVu Sans" \
	  --variable sansfont="DejaVu Sans" \
          -V geometry:"top=3cm, bottom=3cm, left=3.2cm, right=3.2cm" \
	  -V fontsize=11pt \
          -V papersize:a4 \
	  -o Kurzreferenz_git.pdf \
	  Kurzreferenz_git.md

	pandoc \
          --pdf-engine xelatex \
	  --variable mainfont="DejaVu Sans" \
	  --variable sansfont="DejaVu Sans" \
          -V geometry:"top=3cm, bottom=3cm, left=3.2cm, right=3.2cm" \
	  -V fontsize=11pt \
          -V papersize:a4 \
	  -o Kurzreferenz_shell.pdf \
	  Kurzreferenz_shell.md

	pandoc \
          --pdf-engine xelatex \
	  --variable mainfont="DejaVu Sans" \
	  --variable sansfont="DejaVu Sans" \
          -V geometry:"top=3cm, bottom=3cm, left=3.2cm, right=3.2cm" \
	  -V fontsize=11pt \
          -V papersize:a4 \
	  -o Kurzreferenz_markdown.pdf \
	  Kurzreferenz_markdown.md

clean:
	rm -f *pdf *~
