pdf:
	pandoc \
          --pdf-engine xelatex \
	  --variable mainfont="DejaVu Sans" \
	  --variable sansfont="DejaVu Sans" \
          -V geometry:"top=3cm, bottom=3cm, left=3.2cm, right=3.2cm" \
	  -V fontsize=11pt \
          -V papersize:a4 \
	  -o Deutsch_Installation_Python_Git_Bash.pdf \
	  Deutsch_Installation_Python_Git_Bash.md
